controllers:
    resource: ../src/Controller/
    type: annotation

# # commenter pour activer le routage par php
kernel:
    resource: ../src/Kernel.php
    type: annotation

# # avec la gestion des routes dans le yaml:
# home:
#     path: /home
#     controller: App\Controller\HomeController::index
